name: monkeytype
services:
  frontend:
    container_name: monkeytype-frontend
    image: node:18.19.1
    # restart: on-failure
    environment:
      - SERVER_OPEN=false
      - BACKEND_URL=http://localhost:${DOCKER_SERVER_PORT:-5005}
    ports:
      - "${DOCKER_HTTP_PORT:-3000}:3000"
    volumes:
      - root-modules:/monkeytype/node_modules
      - fe-modules:/monkeytype/frontend/node_modules
      - ../../:/monkeytype
    entrypoint: 'bash -c "cd /monkeytype && npm install && cd /monkeytype/frontend && npm install && npm run dev"'
    # entrypoint: "tail -f /dev/null"

volumes:
  root-modules:
  fe-modules:

