name: monkeytype
services:
  frontend:
    container_name: monkeytype-frontend
    image: node:18.17.1
    restart: on-failure
    ports:
      - "3000:3000"
    volumes:
      - ../:/monkeytype
    user: node
    entrypoint: 'bash -c "cd /monkeytype && npm run dev-fe"'
