name: monkeytype
version: "3.8"
services:
  redis:
    container_name: monkeytype-redis
    image: redis:6.2.6
    ports:
      - "${DOCKER_REDIS_PORT:-6379}:${DOCKER_REDIS_PORT:-6379}"
    restart: on-failure
    volumes:
      - redis-data:/data

  mongodb:
    container_name: monkeytype-mongodb
    image: mongo:5.0.8
    restart: on-failure
    volumes:
      - mongo-data:/data/db
    ports:
      - "${DOCKER_DB_PORT:-27017}:${DOCKER_DB_PORT:-27017}"

  api-server:
    container_name: monkeytype-api-server
    image: node:18.17.1
    restart: on-failure
    depends_on:
      - redis
      - mongodb
    environment:
      - DB_URI=mongodb://mongodb:27017
    ports:
      - "${DOCKER_SERVER_PORT:-5005}:${DOCKER_SERVER_PORT:-5005}"
    volumes:
      - ../:/monkeytype
      - /monkeytype/backend/node_modules
    entrypoint: 'bash -c "cd /monkeytype/backend && npm install && npm run dev"'

volumes:
  mongo-data:
  redis-data:
