blank_issues_enabled: false
contact_links:
  - name: Feature Request / Idea
    url: https://github.com/Miodec/monkeytype/discussions
    about: Please do not create issues for feature requests. Instead, use GitHub Discussions.
