name: PR Check

on:
  pull_request:
    branches: [master, dev]

jobs:
  build:
    permissions:
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            any-json:
              - 'frontend/**/*.json'
            language-json:
              - 'frontend/static/languages/*.json'
            quotes-json:
              - 'frontend/static/quotes/*.json'
            other-json:
              - 'frontend/static/funbox/*.json'
              - 'frontend/static/fonts/*.json'
              - 'frontend/static/themes/*.json'
              - 'frontend/static/challenges/*.json'
              - 'frontend/static/layouts/*.json'
            any-tsscss:
              - 'frontend/**/*.scss'
              - 'frontend/**/*.ts'
              - 'backend/**/*.ts'
            ts-scss-fe:
              - 'frontend/**/*.ts'
              - 'frontend/**/*.scss'
            ts-be:
              - 'backend/**/*.ts'
            anti-cheat:
              - 'backend/**/anticheat/**'
            any-src:
              - 'backend/**/*.{ts,js,json}'
              - 'frontend/**/*.{ts,js}'
              - 'frontend/src/**/*.scss'

      - name: Create stub firebase config
        working-directory: ./frontend/src/ts/constants
        run: mv ./firebase-config-example.ts ./firebase-config-live.ts

      - name: Check Anti-cheat
        if: steps.filter.outputs.anti-cheat == 'true'
        run: exit 1

      - name: Save the PR number in an artifact
        shell: bash
        env:
          PR_NUM: ${{ github.event.number }}
        run: echo $PR_NUM > pr_num.txt

      - name: Upload the PR number
        uses: actions/upload-artifact@v2
        with:
          name: pr_num
          path: ./pr_num.txt

      - name: Cache node modules
        if: steps.filter.outputs.changes != '[]'
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Set up Node.js
        if: steps.filter.outputs.changes != '[]'
        uses: actions/setup-node@v1
        with:
          node-version: "16.13.2"

      - name: Install dependencies
        if: steps.filter.outputs.changes != '[]'
        run: npm run install-all

      - name: Pretty Check
        if: steps.filter.outputs.any-src == 'true'
        run: npm run pretty-code

      - name: Lint JSON
        if: steps.filter.outputs.any-json == 'true'
        run: npm run pr-check-lint-json

      - name: Validate languages JSON
        if: steps.filter.outputs.language-json == 'true'
        run: npm run pr-check-language-json

      - name: Validate quotes JSON
        if: steps.filter.outputs.quotes-json == 'true'
        run: npm run pr-check-quote-json

      - name: Validate other JSON
        if: steps.filter.outputs.other-json == 'true'
        run: npm run pr-check-other-json

      - name: Lint
        if: steps.filter.outputs.any-tsscss == 'true'
        run: npm run lint

      - name: Build backend
        if: steps.filter.outputs.ts-be == 'true'
        run: npm run pr-check-build-be

      - name: Test backend
        if: steps.filter.outputs.ts-be == 'true'
        run: npm run test-backend

      - name: Run webpack
        if: steps.filter.outputs.ts-scss-fe == 'true'
        run: npm run pr-check-ts

      - name: Testing new GitHub Job Summaries
        run: |
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
