name: Server CI

on:
  pull_request:
    branches: [master, dev]
  push:
    branches: [master]

jobs:
  pre-build:
    name: pre-build
    permissions:
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            be-src:
              - 'backend/**/*.{ts,js,json,lua,css,html}'
            anti-cheat:
              - 'backend/**/anticheat/**'
      - name: Check Anti-cheat
        if: steps.filter.outputs.anti-cheat == 'true'
        run: exit 1

  build:
    name: build
    needs: [pre-build]
    runs-on: ubuntu-latest
    if: needs.pre-build.outputs.changes != '[]'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.13.2"

      - name: Install dependencies
        run: npm ci & cd backend && npm ci

      - name: Check pretty
        run: npm run pretty-code-be

      - name: Check lint
        run: npm run lint-be

      - name: Build
        run: npm run pr-check-build-be

      - name: Test
        run: npm run test-be
